TRAIN_VOCAB_EN: E:\graduation\code\demo\VMT\src\vocab/train_vocab_en.txt
TRAIN_VOCAB_ZH: E:\graduation\code\demo\VMT\src\vocab/train_vocab_zh.txt
CHK_DIR: E:\graduation\code\demo\VMT\src\model/
DATA_DIR: G:\MSVD\msvd_action_feature/
MAX_INPUT_LENGTH: 40
MAX_VID_LENGTH: 32
seed: 123
model_type: trans_dear
nb_blocks: 6
d_model: 512
att_h: 8
dropout: 0.4
maxlen: 35
warmup_steps: 9600
lr: 0.001
smoothing: 0.3
